main = "src/index.ts"

name = "woof-node-provider-proxy"

compatibility_date = "2026-06-25"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

keep_vars = true

[[kv_namespaces]]
binding = "kv"
id = "ТВОЙ_KV_ID"

[vars]
allowedAppKey = ""
allowedHosts = []

[vars.settings]
maskUpstreamErrors = false
retryWithActiveFallback = false
retryIndividualFailedRpcs = false
defaultFallbackExpirationTtlSeconds = 60
defaultRetryAfterUpstreamErrorSeconds = 5