main = "src/index.ts"

name = 'woof-node-provider-proxy'

compatibility_date = "2026-06-25"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

keep_vars = true

[[kv_namespaces]]
binding = "kv"
id = "57d2fa5ee37346169a2b585f1b66206e"

[vars]
allowedAppKey = ""
allowedHosts = []

# secrets
alchemyEthMainnet = 'ALCHEMY_XXX'
alchemyArbMainnet = 'ALCHEMY_XXX'
alchemyPolygonMainnet = 'ALCHEMY_XXX'
alchemyBaseMainnet = 'ALCHEMY_XXX'
alchemyScrollMainnet = 'ALCHEMY_XXX'
alchemyOptMainnet = 'ALCHEMY_XXX'
alchemyMantleMainnet = 'ALCHEMY_XXX'
alchemyLineaMainnet = 'ALCHEMY_XXX'
alchemyUnichainMainnet = 'ALCHEMY_XXX'
alchemyRoninMainnet = 'ALCHEMY_XXX'
quicknodeEthMainnet = 'QUICK_NODE_XXX'
quicknodeEthMainnetSubdomain = 'QUICK_NODE_XXX'

[vars.settings]
maskUpstreamErrors = false
retryWithActiveFallback = false
retryIndividualFailedRpcs = false
defaultFallbackExpirationTtlSeconds = 60
defaultRetryAfterUpstreamErrorSeconds = 5